# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='run_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.DurationField(),
        ),
    ]
